apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rootca.fullname" . }}--ca
  labels:
{{ include "labels.standard" . | indent 4 }}
data:
  GODEBUG: "netdns=go"
  FABRIC_CA_HOME: /var/hyperledger/fabric-ca
  FABRIC_CA_SERVER_CA_NAME: {{ .Values.caName | quote }}
  SERVICE_DNS: {{ include "rootca.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
