apiVersion: v1
kind: Service
metadata:
  name: {{ include "couchdb.fullname" . }}
  labels:
{{ include "labels.standard" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: couchdb
      protocol: TCP
      name: couchdb
  selector:
    app: {{ include "couchdb.name" . }}
    release: {{ .Release.Name }}
